# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\4_SW_Tool\SW_Project\Python\GUI\Auto_LZ\Auto_LZ_Main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(855, 819)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        MainWindow.setPalette(palette)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(51, 38, 72, 18))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(57, 88, 54, 18))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.lineEdit_username = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_username.setEnabled(True)
        self.lineEdit_username.setGeometry(QtCore.QRect(130, 32, 221, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_username.sizePolicy().hasHeightForWidth())
        self.lineEdit_username.setSizePolicy(sizePolicy)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.lineEdit_password = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_password.setGeometry(QtCore.QRect(130, 80, 221, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_password.sizePolicy().hasHeightForWidth())
        self.lineEdit_password.setSizePolicy(sizePolicy)
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.pushButton_start = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_start.setGeometry(QtCore.QRect(450, 30, 93, 28))
        self.pushButton_start.setObjectName("pushButton_start")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 130, 791, 361))
        self.groupBox.setObjectName("groupBox")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(150, 80, 111, 41))
        self.label_6.setObjectName("label_6")
        self.lineEdit_key_words1 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_key_words1.setGeometry(QtCore.QRect(140, 120, 201, 25))
        self.lineEdit_key_words1.setObjectName("lineEdit_key_words1")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(60, 40, 75, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(410, 40, 75, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_start_date = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_start_date.setGeometry(QtCore.QRect(490, 35, 61, 25))
        self.lineEdit_start_date.setObjectName("lineEdit_start_date")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(30, 90, 45, 16))
        self.label_8.setObjectName("label_8")
        self.lineEdit_end_date = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_end_date.setGeometry(QtCore.QRect(670, 35, 61, 25))
        self.lineEdit_end_date.setObjectName("lineEdit_end_date")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(590, 40, 75, 16))
        self.label_5.setObjectName("label_5")
        self.comboBox_Fun1 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_Fun1.setGeometry(QtCore.QRect(20, 120, 91, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.comboBox_Fun1.setPalette(palette)
        self.comboBox_Fun1.setObjectName("comboBox_Fun1")
        self.comboBox_Veh = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_Veh.setGeometry(QtCore.QRect(140, 35, 111, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.comboBox_Veh.setPalette(palette)
        self.comboBox_Veh.setObjectName("comboBox_Veh")
        self.lineEdit_key_words2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_key_words2.setGeometry(QtCore.QRect(140, 160, 201, 25))
        self.lineEdit_key_words2.setText("")
        self.lineEdit_key_words2.setPlaceholderText("")
        self.lineEdit_key_words2.setObjectName("lineEdit_key_words2")
        self.lineEdit_key_words3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_key_words3.setGeometry(QtCore.QRect(140, 200, 201, 25))
        self.lineEdit_key_words3.setPlaceholderText("")
        self.lineEdit_key_words3.setObjectName("lineEdit_key_words3")
        self.lineEdit_Zep_Address2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Zep_Address2.setGeometry(QtCore.QRect(370, 160, 411, 25))
        self.lineEdit_Zep_Address2.setObjectName("lineEdit_Zep_Address2")
        self.lineEdit_Zep_Address3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Zep_Address3.setGeometry(QtCore.QRect(370, 200, 411, 25))
        self.lineEdit_Zep_Address3.setObjectName("lineEdit_Zep_Address3")
        self.comboBox_Fun2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_Fun2.setGeometry(QtCore.QRect(20, 160, 91, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.comboBox_Fun2.setPalette(palette)
        self.comboBox_Fun2.setObjectName("comboBox_Fun2")
        self.lineEdit_Zep_Address1 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Zep_Address1.setGeometry(QtCore.QRect(370, 120, 411, 25))
        self.lineEdit_Zep_Address1.setObjectName("lineEdit_Zep_Address1")
        self.comboBox_Fun3 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_Fun3.setGeometry(QtCore.QRect(20, 200, 91, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.comboBox_Fun3.setPalette(palette)
        self.comboBox_Fun3.setObjectName("comboBox_Fun3")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(370, 90, 136, 16))
        self.label_7.setObjectName("label_7")
        self.pushButton_edit = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_edit.setGeometry(QtCore.QRect(260, 35, 51, 28))
        self.pushButton_edit.setObjectName("pushButton_edit")
        self.checkBox_address_link = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_address_link.setGeometry(QtCore.QRect(500, 90, 121, 16))
        self.checkBox_address_link.setObjectName("checkBox_address_link")
        self.pushButton_address_setting = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_address_setting.setGeometry(QtCore.QRect(720, 85, 51, 25))
        self.pushButton_address_setting.setObjectName("pushButton_address_setting")
        self.lineEdit_Zep_Address4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Zep_Address4.setGeometry(QtCore.QRect(370, 240, 411, 25))
        self.lineEdit_Zep_Address4.setObjectName("lineEdit_Zep_Address4")
        self.lineEdit_key_words4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_key_words4.setGeometry(QtCore.QRect(140, 240, 201, 25))
        self.lineEdit_key_words4.setPlaceholderText("")
        self.lineEdit_key_words4.setObjectName("lineEdit_key_words4")
        self.comboBox_Fun4 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_Fun4.setGeometry(QtCore.QRect(20, 240, 91, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.comboBox_Fun4.setPalette(palette)
        self.comboBox_Fun4.setObjectName("comboBox_Fun4")
        self.comboBox_Fun5 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_Fun5.setGeometry(QtCore.QRect(20, 280, 91, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.comboBox_Fun5.setPalette(palette)
        self.comboBox_Fun5.setObjectName("comboBox_Fun5")
        self.lineEdit_key_words5 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_key_words5.setGeometry(QtCore.QRect(140, 280, 201, 25))
        self.lineEdit_key_words5.setPlaceholderText("")
        self.lineEdit_key_words5.setObjectName("lineEdit_key_words5")
        self.comboBox_Fun6 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_Fun6.setGeometry(QtCore.QRect(20, 320, 91, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.comboBox_Fun6.setPalette(palette)
        self.comboBox_Fun6.setObjectName("comboBox_Fun6")
        self.lineEdit_Zep_Address5 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Zep_Address5.setGeometry(QtCore.QRect(370, 280, 411, 25))
        self.lineEdit_Zep_Address5.setObjectName("lineEdit_Zep_Address5")
        self.lineEdit_key_words6 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_key_words6.setGeometry(QtCore.QRect(140, 320, 201, 25))
        self.lineEdit_key_words6.setPlaceholderText("")
        self.lineEdit_key_words6.setObjectName("lineEdit_key_words6")
        self.lineEdit_Zep_Address6 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Zep_Address6.setGeometry(QtCore.QRect(370, 320, 411, 25))
        self.lineEdit_Zep_Address6.setObjectName("lineEdit_Zep_Address6")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(40, 500, 781, 301))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.tabWidget.setPalette(palette)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.tab.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tab.setFont(font)
        self.tab.setObjectName("tab")
        self.textEdit_p_info = QtWidgets.QTextEdit(self.tab)
        self.textEdit_p_info.setGeometry(QtCore.QRect(0, 0, 781, 281))
        self.textEdit_p_info.setObjectName("textEdit_p_info")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.textEdit_e_info = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_e_info.setGeometry(QtCore.QRect(0, 0, 781, 301))
        self.textEdit_e_info.setObjectName("textEdit_e_info")
        self.tabWidget.addTab(self.tab_2, "")
        self.checkBox_Skip = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_Skip.setGeometry(QtCore.QRect(610, 30, 131, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.checkBox_Skip.setFont(font)
        self.checkBox_Skip.setObjectName("checkBox_Skip")
        self.checkBox_file = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_file.setGeometry(QtCore.QRect(610, 60, 131, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.checkBox_file.setFont(font)
        self.checkBox_file.setObjectName("checkBox_file")
        self.checkBox_browser = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_browser.setGeometry(QtCore.QRect(610, 90, 111, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.checkBox_browser.setFont(font)
        self.checkBox_browser.setObjectName("checkBox_browser")
        self.pushButton_end = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_end.setGeometry(QtCore.QRect(450, 80, 93, 28))
        self.pushButton_end.setObjectName("pushButton_end")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "用户名："))
        self.label_2.setText(_translate("MainWindow", "密码："))
        self.lineEdit_username.setPlaceholderText(_translate("MainWindow", "NIO邮箱"))
        self.lineEdit_password.setPlaceholderText(_translate("MainWindow", "NIO密码"))
        self.pushButton_start.setText(_translate("MainWindow", "开始分析 "))
        self.groupBox.setTitle(_translate("MainWindow", "Luna检索信息"))
        self.label_6.setText(_translate("MainWindow", "关键字："))
        self.lineEdit_key_words1.setPlaceholderText(_translate("MainWindow", "Pilot退出|ACC退出 "))
        self.label_3.setText(_translate("MainWindow", "车辆编码："))
        self.label_4.setText(_translate("MainWindow", "起始日期："))
        self.lineEdit_start_date.setPlaceholderText(_translate("MainWindow", "5.1"))
        self.label_8.setText(_translate("MainWindow", "功能："))
        self.lineEdit_end_date.setPlaceholderText(_translate("MainWindow", "5.2"))
        self.label_5.setText(_translate("MainWindow", "终止日期："))
        self.label_7.setText(_translate("MainWindow", "Zeppelin 地址:"))
        self.pushButton_edit.setText(_translate("MainWindow", "编辑"))
        self.checkBox_address_link.setText(_translate("MainWindow", "地址自动配置"))
        self.pushButton_address_setting.setText(_translate("MainWindow", "设置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "进度信息"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "报错信息"))
        self.checkBox_Skip.setText(_translate("MainWindow", "覆盖已分析的Tag"))
        self.checkBox_file.setText(_translate("MainWindow", "生成分析列表清单"))
        self.checkBox_browser.setText(_translate("MainWindow", "显示浏览器"))
        self.pushButton_end.setText(_translate("MainWindow", "暂停分析"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

